# Generated by Django 3.2.15 on 2022-09-23 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(max_length=200, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Job Categories',
            },
        ),
        migrations.CreateModel(
            name='JobSkillSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_name', models.CharField(max_length=255, verbose_name='Skill Name')),
            ],
            options={
                'verbose_name_plural': 'Job Skill Set',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('job_description', models.TextField(verbose_name='Job Description')),
                ('recruitment_start_date', models.DateField(verbose_name='Recruitment Start Date')),
                ('recruitment_end_date', models.DateField(verbose_name='Recruitment End Date')),
                ('recruitment_quota', models.CharField(max_length=255, verbose_name='Recruitment Quota')),
                ('location', models.CharField(max_length=255)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='employer.hiring', verbose_name='Job Created By')),
                ('skill_set', models.ManyToManyField(to='jobs.JobSkillSet', verbose_name='Job Skill Sets')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
