# Generated by Django 3.2.15 on 2022-09-24 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeker',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='updated_at',
        ),
    ]
